server:
  port: 12345

spring:
  main:
    web-application-type: reactive # 因为引入common模块内有spring-boot-starter-web
  application:
    name: gateway # 服务名称

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.101:8848 # Nacos地址
        enabled: true # 开启服务发现
    loadbalancer:
      configurations: default
      retry:
        enabled: true # 开启重试

    gateway:
      discovery:
        locator:
          enabled: true # 开启网关
      httpclient:
        connect-timeout: 3000
        response-timeout: 10s

      routes: # 网关路由配置
        - id: user-service
          uri: lb://user-service # 路由目标地址     lb:// 格式代表 LoadBalancer 负载均衡支持
          predicates: # 路由断言: 判断收到的请求是否符合路由的要求
            - Path=/users/** # 路径匹配

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
#      default-filters: # 默认拦截器  对所有请求有效
#        - PrefixPath=/DuJiaCun # 为所有请求添加前缀
        #配合order-service中的(server.servlet.context-path=/DuJiaCun)一起使用
  data:
    redis:
      host: 192.168.0.152
      port: 6379
      password: root


#logging:
#  level:
#    org.springframework.cloud.gateway: TRACE
#    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: TRACE
#    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE
#    org.springframework.web.reactive: DEBUG