
spring.application.name=user-service
server.port=8080

#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/DuJiaCun_Cloud_User
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

mybatis.mapper-locations= classpath:mapper/*.xml

#JWT
app.jwt.secret=MySuperSecretKeyForJWTAuthThatIsLongEnough32Bytes
app.jwt.expiration=86400000

#redis
spring.data.redis.host=192.168.0.152
spring.data.redis.port=6379
spring.data.redis.password=root
spring.redis.lettuce.pool.max-active=8
spring.redis.lettuce.pool.max-idle=8
spring.redis.lettuce.pool.min-idle=1
spring.redis.lettuce.pool.max-wait=10s

#log
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

#Nacos
spring.cloud.nacos.discovery.server-addr=192.168.0.101:8848
# ??????
spring.cloud.nacos.discovery.cluster-name=SY