spring:
  application:
    name: order-service
  cloud:
    loadbalancer:
      retry:
        enabled: false # 控制负载均衡的重试功能 :存在多个健康的实例时,会触发一次重试
      nacos:
        enabled: true # Nacos 特有的负载均衡配置 , 关闭变成 Spring Cloud LoadBalancer 的默认策略
    openfeign:
      sentinel: # 开启Sentinel的集成
          enabled: true # 必须设置为true，Sentinel才能对Feign接口生效
      client:
        config:
          default: #全局默认设置
#            retryer: feign.Retryer.NEVER_RETRY # 关闭feign重试
            connect-timeout: 3000 # 连接超时3秒
            read-timeout: 6000 # 读取超时6秒 , 需要大于seata的超时时间
    sentinel:
      transport:
        dashboard: localhost:8050 # sentinel控制台地址
        eager: true # 启动时立即初始化Sentinel
      datasource:
        create-order-flow:
          file:
            file: classpath:sentinel/create-order-flow-rules.json # 本地创建订单限流规则
            data-type: json
            rule-type: flow
        create-order-degrade:
          file:
            file: classpath:sentinel/create-order-degrade-rules.json # 本地创建订单熔断降级规则
            data-type: json
            rule-type: degrade

  datasource:
    url: jdbc:postgresql://localhost:5432/DuJiaCun_Cloud_Order
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: 192.168.0.152
      port: 6379
      password: root
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 1
          max-wait: 10s
  rabbitmq:
    host: localhost
    port: 5672
    username: zjh
    password: root
    virtual-host: zjh_host      # 虚拟主机
    # 生产者可靠性配置
    publisher-confirm-type: correlated  # 开启生产者确认，确认消息是否到达交换机
    publisher-returns: true             # 消息路由失败时回调
    template:
      mandatory: true                 # 消息无法路由到队列时触发 ReturnsCallback。
    # 消费者可靠性配置
    listener:
      simple:
        acknowledge-mode: manual      # **必须手动ACK**，避免消息丢失
        prefetch: 5                  # 单次拉取消息数，防消费者过载
        retry:
          enabled: true              # 开启消费失败重试
          max-attempts: 3            # 最大重试次数

server:
  port: 9080

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

seata:
  enable-auto-data-source-proxy: true
  store-mode: db
  tx-service-group: default_tx_group

  service:
    vgroup-mapping:
      default_tx_group: default
    grouplist:
      default: 127.0.0.1:8091
    timeout: 5000 # 默认超时时间 5 秒
  registry:
    type: file
  config:
    type: file

  client:
    tm:
      # 全局事务超时时间（毫秒），默认60000
      default-global-transaction-timeout: 30000
      # 回滚重试次数
      rollback-retry-count: 3
      # 异步提交超时（毫秒）
      async-commit-timeout: 10000


